Revert "Use Credentials from GcpOptions instead of BigtableOptions"
This reverts commit 0ebb7a1edb98c035b54d382a2e2d77331dac829a.

Fails in BigtableWriteIT#testE2EBigtableWrite

java.lang.NoSuchMethodError: com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(Lcom/google/api/client/http/HttpTransport;)Lcom/google/auth/oauth2/GoogleCredentials;
    at com.google.cloud.bigtable.config.CredentialFactory.getApplicationDefaultCredential(CredentialFactory.java:207)
    at com.google.cloud.bigtable.config.CredentialFactory.getCredentials(CredentialFactory.java:112)
    at com.google.cloud.bigtable.grpc.io.CredentialInterceptorCache.getCredentialsInterceptor(CredentialInterceptorCache.java:94)
    at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:272)
    at org.apache.beam.sdk.io.gcp.bigtable.BigtableWriteIT.setup(BigtableWriteIT.java:93)